
import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import Footer from '@/components/Footer/Footer'
// import { Provider } from "react-redux";
// import { PersistGate } from "redux-persist/integration/react";
// import { persistor, store } from '@/redux/store';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* <Provider store={store}>
          <PersistGate loading={"loading"} persistor={persistor}> */}
        {/* <Navbar /> */}
        {children}
        <Footer />
        {/* </PersistGate>
        </Provider> */}
      </body>
    </html>
  )
}
